{
    "cells": [
        {
            "cell_type": "code",
            "execution_count": 1,
            "source": [
                "\"\"\"\n",
                "@Author: Swapnil Bhoyar\n",
                "@Date: 2021-07-13 \n",
                "@Last Modified by: Swapnil Bhoyar\n",
                "@Last Modified time: 2021-08-13\n",
                "@Title : Write a Python program to iterate over rows in a DataFrame.\n",
                "\"\"\"\n",
                "import pandas as pd\n",
                "import numpy as np\n",
                "import Log\n",
                "\n",
                "def iterateOverRow():\n",
                "    try:\n",
                "        exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],\n",
                "            'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],\n",
                "            'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],\n",
                "            'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}\n",
                "        labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']\n",
                "\n",
                "        tempDataframe = pd.DataFrame(exam_data , index=labels)\n",
                "        for index, row in tempDataframe.iterrows():\n",
                "            print(row['name'], row['qualify'])\n",
                "    except Exception as e:\n",
                "        Log.logging.info(e)\n",
                "\n",
                "iterateOverRow()"
            ],
            "outputs": [
                {
                    "output_type": "stream",
                    "name": "stderr",
                    "text": [
                        "--- Logging error ---\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1085, in emit\n",
                        "    msg = self.format(record)\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 929, in format\n",
                        "    return fmt.format(record)\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 668, in format\n",
                        "    record.message = record.getMessage()\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 373, in getMessage\n",
                        "    msg = msg % self.args\n",
                        "TypeError: not all arguments converted during string formatting\n",
                        "Call stack:\n",
                        "  File \"/usr/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n",
                        "    return _run_code(code, main_globals, None,\n",
                        "  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n",
                        "    exec(code, run_globals)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
                        "    app.launch_new_instance()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/traitlets/config/application.py\", line 845, in launch_instance\n",
                        "    app.start()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 668, in start\n",
                        "    self.io_loop.start()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n",
                        "    self.asyncio_loop.run_forever()\n",
                        "  File \"/usr/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n",
                        "    self._run_once()\n",
                        "  File \"/usr/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n",
                        "    handle._run()\n",
                        "  File \"/usr/lib/python3.8/asyncio/events.py\", line 81, in _run\n",
                        "    self._context.run(self._callback, *self._args)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 456, in dispatch_queue\n",
                        "    await self.process_one()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 445, in process_one\n",
                        "    await dispatch(*args)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 352, in dispatch_shell\n",
                        "    await result\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 647, in execute_request\n",
                        "    reply_content = await reply_content\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 335, in do_execute\n",
                        "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 532, in run_cell\n",
                        "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2898, in run_cell\n",
                        "    result = self._run_cell(\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2944, in _run_cell\n",
                        "    return runner(coro)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
                        "    coro.send(None)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3169, in run_cell_async\n",
                        "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3361, in run_ast_nodes\n",
                        "    if (await self.run_code(code, result,  async_=asy)):\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3441, in run_code\n",
                        "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
                        "  File \"/tmp/ipykernel_6479/1223053753.py\", line 26, in <module>\n",
                        "    iterateOverRow()\n",
                        "  File \"/tmp/ipykernel_6479/1223053753.py\", line 22, in iterateOverRow\n",
                        "    Log.logging.info(row['name'], row['qualify'])\n",
                        "Message: 'Anastasia'\n",
                        "Arguments: ('yes',)\n",
                        "--- Logging error ---\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1085, in emit\n",
                        "    msg = self.format(record)\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 929, in format\n",
                        "    return fmt.format(record)\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 668, in format\n",
                        "    record.message = record.getMessage()\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 373, in getMessage\n",
                        "    msg = msg % self.args\n",
                        "TypeError: not all arguments converted during string formatting\n",
                        "Call stack:\n",
                        "  File \"/usr/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n",
                        "    return _run_code(code, main_globals, None,\n",
                        "  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n",
                        "    exec(code, run_globals)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
                        "    app.launch_new_instance()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/traitlets/config/application.py\", line 845, in launch_instance\n",
                        "    app.start()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 668, in start\n",
                        "    self.io_loop.start()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n",
                        "    self.asyncio_loop.run_forever()\n",
                        "  File \"/usr/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n",
                        "    self._run_once()\n",
                        "  File \"/usr/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n",
                        "    handle._run()\n",
                        "  File \"/usr/lib/python3.8/asyncio/events.py\", line 81, in _run\n",
                        "    self._context.run(self._callback, *self._args)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 456, in dispatch_queue\n",
                        "    await self.process_one()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 445, in process_one\n",
                        "    await dispatch(*args)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 352, in dispatch_shell\n",
                        "    await result\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 647, in execute_request\n",
                        "    reply_content = await reply_content\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 335, in do_execute\n",
                        "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 532, in run_cell\n",
                        "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2898, in run_cell\n",
                        "    result = self._run_cell(\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2944, in _run_cell\n",
                        "    return runner(coro)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
                        "    coro.send(None)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3169, in run_cell_async\n",
                        "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3361, in run_ast_nodes\n",
                        "    if (await self.run_code(code, result,  async_=asy)):\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3441, in run_code\n",
                        "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
                        "  File \"/tmp/ipykernel_6479/1223053753.py\", line 26, in <module>\n",
                        "    iterateOverRow()\n",
                        "  File \"/tmp/ipykernel_6479/1223053753.py\", line 22, in iterateOverRow\n",
                        "    Log.logging.info(row['name'], row['qualify'])\n",
                        "Message: 'Dima'\n",
                        "Arguments: ('no',)\n",
                        "--- Logging error ---\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1085, in emit\n",
                        "    msg = self.format(record)\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 929, in format\n",
                        "    return fmt.format(record)\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 668, in format\n",
                        "    record.message = record.getMessage()\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 373, in getMessage\n",
                        "    msg = msg % self.args\n",
                        "TypeError: not all arguments converted during string formatting\n",
                        "Call stack:\n",
                        "  File \"/usr/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n",
                        "    return _run_code(code, main_globals, None,\n",
                        "  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n",
                        "    exec(code, run_globals)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
                        "    app.launch_new_instance()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/traitlets/config/application.py\", line 845, in launch_instance\n",
                        "    app.start()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 668, in start\n",
                        "    self.io_loop.start()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n",
                        "    self.asyncio_loop.run_forever()\n",
                        "  File \"/usr/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n",
                        "    self._run_once()\n",
                        "  File \"/usr/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n",
                        "    handle._run()\n",
                        "  File \"/usr/lib/python3.8/asyncio/events.py\", line 81, in _run\n",
                        "    self._context.run(self._callback, *self._args)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 456, in dispatch_queue\n",
                        "    await self.process_one()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 445, in process_one\n",
                        "    await dispatch(*args)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 352, in dispatch_shell\n",
                        "    await result\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 647, in execute_request\n",
                        "    reply_content = await reply_content\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 335, in do_execute\n",
                        "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 532, in run_cell\n",
                        "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2898, in run_cell\n",
                        "    result = self._run_cell(\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2944, in _run_cell\n",
                        "    return runner(coro)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
                        "    coro.send(None)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3169, in run_cell_async\n",
                        "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3361, in run_ast_nodes\n",
                        "    if (await self.run_code(code, result,  async_=asy)):\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3441, in run_code\n",
                        "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
                        "  File \"/tmp/ipykernel_6479/1223053753.py\", line 26, in <module>\n",
                        "    iterateOverRow()\n",
                        "  File \"/tmp/ipykernel_6479/1223053753.py\", line 22, in iterateOverRow\n",
                        "    Log.logging.info(row['name'], row['qualify'])\n",
                        "Message: 'Katherine'\n",
                        "Arguments: ('yes',)\n",
                        "--- Logging error ---\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1085, in emit\n",
                        "    msg = self.format(record)\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 929, in format\n",
                        "    return fmt.format(record)\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 668, in format\n",
                        "    record.message = record.getMessage()\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 373, in getMessage\n",
                        "    msg = msg % self.args\n",
                        "TypeError: not all arguments converted during string formatting\n",
                        "Call stack:\n",
                        "  File \"/usr/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n",
                        "    return _run_code(code, main_globals, None,\n",
                        "  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n",
                        "    exec(code, run_globals)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
                        "    app.launch_new_instance()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/traitlets/config/application.py\", line 845, in launch_instance\n",
                        "    app.start()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 668, in start\n",
                        "    self.io_loop.start()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n",
                        "    self.asyncio_loop.run_forever()\n",
                        "  File \"/usr/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n",
                        "    self._run_once()\n",
                        "  File \"/usr/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n",
                        "    handle._run()\n",
                        "  File \"/usr/lib/python3.8/asyncio/events.py\", line 81, in _run\n",
                        "    self._context.run(self._callback, *self._args)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 456, in dispatch_queue\n",
                        "    await self.process_one()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 445, in process_one\n",
                        "    await dispatch(*args)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 352, in dispatch_shell\n",
                        "    await result\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 647, in execute_request\n",
                        "    reply_content = await reply_content\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 335, in do_execute\n",
                        "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 532, in run_cell\n",
                        "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2898, in run_cell\n",
                        "    result = self._run_cell(\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2944, in _run_cell\n",
                        "    return runner(coro)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
                        "    coro.send(None)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3169, in run_cell_async\n",
                        "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3361, in run_ast_nodes\n",
                        "    if (await self.run_code(code, result,  async_=asy)):\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3441, in run_code\n",
                        "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
                        "  File \"/tmp/ipykernel_6479/1223053753.py\", line 26, in <module>\n",
                        "    iterateOverRow()\n",
                        "  File \"/tmp/ipykernel_6479/1223053753.py\", line 22, in iterateOverRow\n",
                        "    Log.logging.info(row['name'], row['qualify'])\n",
                        "Message: 'James'\n",
                        "Arguments: ('no',)\n",
                        "--- Logging error ---\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1085, in emit\n",
                        "    msg = self.format(record)\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 929, in format\n",
                        "    return fmt.format(record)\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 668, in format\n",
                        "    record.message = record.getMessage()\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 373, in getMessage\n",
                        "    msg = msg % self.args\n",
                        "TypeError: not all arguments converted during string formatting\n",
                        "Call stack:\n",
                        "  File \"/usr/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n",
                        "    return _run_code(code, main_globals, None,\n",
                        "  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n",
                        "    exec(code, run_globals)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
                        "    app.launch_new_instance()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/traitlets/config/application.py\", line 845, in launch_instance\n",
                        "    app.start()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 668, in start\n",
                        "    self.io_loop.start()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n",
                        "    self.asyncio_loop.run_forever()\n",
                        "  File \"/usr/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n",
                        "    self._run_once()\n",
                        "  File \"/usr/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n",
                        "    handle._run()\n",
                        "  File \"/usr/lib/python3.8/asyncio/events.py\", line 81, in _run\n",
                        "    self._context.run(self._callback, *self._args)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 456, in dispatch_queue\n",
                        "    await self.process_one()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 445, in process_one\n",
                        "    await dispatch(*args)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 352, in dispatch_shell\n",
                        "    await result\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 647, in execute_request\n",
                        "    reply_content = await reply_content\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 335, in do_execute\n",
                        "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 532, in run_cell\n",
                        "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2898, in run_cell\n",
                        "    result = self._run_cell(\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2944, in _run_cell\n",
                        "    return runner(coro)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
                        "    coro.send(None)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3169, in run_cell_async\n",
                        "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3361, in run_ast_nodes\n",
                        "    if (await self.run_code(code, result,  async_=asy)):\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3441, in run_code\n",
                        "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
                        "  File \"/tmp/ipykernel_6479/1223053753.py\", line 26, in <module>\n",
                        "    iterateOverRow()\n",
                        "  File \"/tmp/ipykernel_6479/1223053753.py\", line 22, in iterateOverRow\n",
                        "    Log.logging.info(row['name'], row['qualify'])\n",
                        "Message: 'Emily'\n",
                        "Arguments: ('no',)\n",
                        "--- Logging error ---\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1085, in emit\n",
                        "    msg = self.format(record)\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 929, in format\n",
                        "    return fmt.format(record)\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 668, in format\n",
                        "    record.message = record.getMessage()\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 373, in getMessage\n",
                        "    msg = msg % self.args\n",
                        "TypeError: not all arguments converted during string formatting\n",
                        "Call stack:\n",
                        "  File \"/usr/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n",
                        "    return _run_code(code, main_globals, None,\n",
                        "  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n",
                        "    exec(code, run_globals)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
                        "    app.launch_new_instance()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/traitlets/config/application.py\", line 845, in launch_instance\n",
                        "    app.start()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 668, in start\n",
                        "    self.io_loop.start()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n",
                        "    self.asyncio_loop.run_forever()\n",
                        "  File \"/usr/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n",
                        "    self._run_once()\n",
                        "  File \"/usr/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n",
                        "    handle._run()\n",
                        "  File \"/usr/lib/python3.8/asyncio/events.py\", line 81, in _run\n",
                        "    self._context.run(self._callback, *self._args)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 456, in dispatch_queue\n",
                        "    await self.process_one()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 445, in process_one\n",
                        "    await dispatch(*args)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 352, in dispatch_shell\n",
                        "    await result\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 647, in execute_request\n",
                        "    reply_content = await reply_content\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 335, in do_execute\n",
                        "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 532, in run_cell\n",
                        "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2898, in run_cell\n",
                        "    result = self._run_cell(\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2944, in _run_cell\n",
                        "    return runner(coro)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
                        "    coro.send(None)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3169, in run_cell_async\n",
                        "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3361, in run_ast_nodes\n",
                        "    if (await self.run_code(code, result,  async_=asy)):\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3441, in run_code\n",
                        "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
                        "  File \"/tmp/ipykernel_6479/1223053753.py\", line 26, in <module>\n",
                        "    iterateOverRow()\n",
                        "  File \"/tmp/ipykernel_6479/1223053753.py\", line 22, in iterateOverRow\n",
                        "    Log.logging.info(row['name'], row['qualify'])\n",
                        "Message: 'Michael'\n",
                        "Arguments: ('yes',)\n",
                        "--- Logging error ---\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1085, in emit\n",
                        "    msg = self.format(record)\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 929, in format\n",
                        "    return fmt.format(record)\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 668, in format\n",
                        "    record.message = record.getMessage()\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 373, in getMessage\n",
                        "    msg = msg % self.args\n",
                        "TypeError: not all arguments converted during string formatting\n",
                        "Call stack:\n",
                        "  File \"/usr/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n",
                        "    return _run_code(code, main_globals, None,\n",
                        "  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n",
                        "    exec(code, run_globals)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
                        "    app.launch_new_instance()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/traitlets/config/application.py\", line 845, in launch_instance\n",
                        "    app.start()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 668, in start\n",
                        "    self.io_loop.start()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n",
                        "    self.asyncio_loop.run_forever()\n",
                        "  File \"/usr/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n",
                        "    self._run_once()\n",
                        "  File \"/usr/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n",
                        "    handle._run()\n",
                        "  File \"/usr/lib/python3.8/asyncio/events.py\", line 81, in _run\n",
                        "    self._context.run(self._callback, *self._args)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 456, in dispatch_queue\n",
                        "    await self.process_one()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 445, in process_one\n",
                        "    await dispatch(*args)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 352, in dispatch_shell\n",
                        "    await result\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 647, in execute_request\n",
                        "    reply_content = await reply_content\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 335, in do_execute\n",
                        "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 532, in run_cell\n",
                        "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2898, in run_cell\n",
                        "    result = self._run_cell(\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2944, in _run_cell\n",
                        "    return runner(coro)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
                        "    coro.send(None)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3169, in run_cell_async\n",
                        "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3361, in run_ast_nodes\n",
                        "    if (await self.run_code(code, result,  async_=asy)):\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3441, in run_code\n",
                        "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
                        "  File \"/tmp/ipykernel_6479/1223053753.py\", line 26, in <module>\n",
                        "    iterateOverRow()\n",
                        "  File \"/tmp/ipykernel_6479/1223053753.py\", line 22, in iterateOverRow\n",
                        "    Log.logging.info(row['name'], row['qualify'])\n",
                        "Message: 'Matthew'\n",
                        "Arguments: ('yes',)\n",
                        "--- Logging error ---\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1085, in emit\n",
                        "    msg = self.format(record)\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 929, in format\n",
                        "    return fmt.format(record)\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 668, in format\n",
                        "    record.message = record.getMessage()\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 373, in getMessage\n",
                        "    msg = msg % self.args\n",
                        "TypeError: not all arguments converted during string formatting\n",
                        "Call stack:\n",
                        "  File \"/usr/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n",
                        "    return _run_code(code, main_globals, None,\n",
                        "  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n",
                        "    exec(code, run_globals)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
                        "    app.launch_new_instance()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/traitlets/config/application.py\", line 845, in launch_instance\n",
                        "    app.start()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 668, in start\n",
                        "    self.io_loop.start()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n",
                        "    self.asyncio_loop.run_forever()\n",
                        "  File \"/usr/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n",
                        "    self._run_once()\n",
                        "  File \"/usr/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n",
                        "    handle._run()\n",
                        "  File \"/usr/lib/python3.8/asyncio/events.py\", line 81, in _run\n",
                        "    self._context.run(self._callback, *self._args)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 456, in dispatch_queue\n",
                        "    await self.process_one()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 445, in process_one\n",
                        "    await dispatch(*args)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 352, in dispatch_shell\n",
                        "    await result\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 647, in execute_request\n",
                        "    reply_content = await reply_content\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 335, in do_execute\n",
                        "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 532, in run_cell\n",
                        "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2898, in run_cell\n",
                        "    result = self._run_cell(\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2944, in _run_cell\n",
                        "    return runner(coro)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
                        "    coro.send(None)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3169, in run_cell_async\n",
                        "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3361, in run_ast_nodes\n",
                        "    if (await self.run_code(code, result,  async_=asy)):\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3441, in run_code\n",
                        "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
                        "  File \"/tmp/ipykernel_6479/1223053753.py\", line 26, in <module>\n",
                        "    iterateOverRow()\n",
                        "  File \"/tmp/ipykernel_6479/1223053753.py\", line 22, in iterateOverRow\n",
                        "    Log.logging.info(row['name'], row['qualify'])\n",
                        "Message: 'Laura'\n",
                        "Arguments: ('no',)\n",
                        "--- Logging error ---\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1085, in emit\n",
                        "    msg = self.format(record)\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 929, in format\n",
                        "    return fmt.format(record)\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 668, in format\n",
                        "    record.message = record.getMessage()\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 373, in getMessage\n",
                        "    msg = msg % self.args\n",
                        "TypeError: not all arguments converted during string formatting\n",
                        "Call stack:\n",
                        "  File \"/usr/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n",
                        "    return _run_code(code, main_globals, None,\n",
                        "  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n",
                        "    exec(code, run_globals)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
                        "    app.launch_new_instance()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/traitlets/config/application.py\", line 845, in launch_instance\n",
                        "    app.start()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 668, in start\n",
                        "    self.io_loop.start()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n",
                        "    self.asyncio_loop.run_forever()\n",
                        "  File \"/usr/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n",
                        "    self._run_once()\n",
                        "  File \"/usr/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n",
                        "    handle._run()\n",
                        "  File \"/usr/lib/python3.8/asyncio/events.py\", line 81, in _run\n",
                        "    self._context.run(self._callback, *self._args)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 456, in dispatch_queue\n",
                        "    await self.process_one()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 445, in process_one\n",
                        "    await dispatch(*args)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 352, in dispatch_shell\n",
                        "    await result\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 647, in execute_request\n",
                        "    reply_content = await reply_content\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 335, in do_execute\n",
                        "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 532, in run_cell\n",
                        "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2898, in run_cell\n",
                        "    result = self._run_cell(\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2944, in _run_cell\n",
                        "    return runner(coro)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
                        "    coro.send(None)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3169, in run_cell_async\n",
                        "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3361, in run_ast_nodes\n",
                        "    if (await self.run_code(code, result,  async_=asy)):\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3441, in run_code\n",
                        "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
                        "  File \"/tmp/ipykernel_6479/1223053753.py\", line 26, in <module>\n",
                        "    iterateOverRow()\n",
                        "  File \"/tmp/ipykernel_6479/1223053753.py\", line 22, in iterateOverRow\n",
                        "    Log.logging.info(row['name'], row['qualify'])\n",
                        "Message: 'Kevin'\n",
                        "Arguments: ('no',)\n",
                        "--- Logging error ---\n",
                        "Traceback (most recent call last):\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 1085, in emit\n",
                        "    msg = self.format(record)\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 929, in format\n",
                        "    return fmt.format(record)\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 668, in format\n",
                        "    record.message = record.getMessage()\n",
                        "  File \"/usr/lib/python3.8/logging/__init__.py\", line 373, in getMessage\n",
                        "    msg = msg % self.args\n",
                        "TypeError: not all arguments converted during string formatting\n",
                        "Call stack:\n",
                        "  File \"/usr/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n",
                        "    return _run_code(code, main_globals, None,\n",
                        "  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n",
                        "    exec(code, run_globals)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel_launcher.py\", line 16, in <module>\n",
                        "    app.launch_new_instance()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/traitlets/config/application.py\", line 845, in launch_instance\n",
                        "    app.start()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 668, in start\n",
                        "    self.io_loop.start()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 199, in start\n",
                        "    self.asyncio_loop.run_forever()\n",
                        "  File \"/usr/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n",
                        "    self._run_once()\n",
                        "  File \"/usr/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n",
                        "    handle._run()\n",
                        "  File \"/usr/lib/python3.8/asyncio/events.py\", line 81, in _run\n",
                        "    self._context.run(self._callback, *self._args)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 456, in dispatch_queue\n",
                        "    await self.process_one()\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 445, in process_one\n",
                        "    await dispatch(*args)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 352, in dispatch_shell\n",
                        "    await result\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 647, in execute_request\n",
                        "    reply_content = await reply_content\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 335, in do_execute\n",
                        "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 532, in run_cell\n",
                        "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2898, in run_cell\n",
                        "    result = self._run_cell(\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2944, in _run_cell\n",
                        "    return runner(coro)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n",
                        "    coro.send(None)\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3169, in run_cell_async\n",
                        "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3361, in run_ast_nodes\n",
                        "    if (await self.run_code(code, result,  async_=asy)):\n",
                        "  File \"/home/neo/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3441, in run_code\n",
                        "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
                        "  File \"/tmp/ipykernel_6479/1223053753.py\", line 26, in <module>\n",
                        "    iterateOverRow()\n",
                        "  File \"/tmp/ipykernel_6479/1223053753.py\", line 22, in iterateOverRow\n",
                        "    Log.logging.info(row['name'], row['qualify'])\n",
                        "Message: 'Jonas'\n",
                        "Arguments: ('yes',)\n"
                    ]
                }
            ],
            "metadata": {}
        }
    ],
    "metadata": {
        "orig_nbformat": 4,
        "language_info": {
            "name": "python"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 2
}